IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/DCASE_experiments/SSL-Efficientnet_frame257/dcase2021_task2'
  PREMODEL_ROOT: '/home/hiroki/research/dcase2021_task2/input/PANNs/pre_trained_model/ResNet38_mAP=0.434.pth'
  
param:
  # feature
  sample_rate: 16000
  window_size: 2048
  hop_size: 320
  mel_bins: 128
  fmin: 50
  fmax: 7800
  n_crop_frames : 128
  extract_hop_len : 5
  # dataloader
  lr : 0.001
  batch_size : 256
  shuffle : True
  num_epochs : 200
  # etc
  devise : 'cuda'
  max_fpr : 0.1
